name: control_gastos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.13.5
  firebase_database: ^11.2.0
  cloud_firestore: ^5.6.0
  intl: ^0.20.2
  path_provider: ^2.0.11
  logger: ^2.5.0     
  shared_preferences: ^2.3.4
  provider: ^6.0.5
  uuid: ^4.5.1
  rxdart: ^0.28.0
  async: ^2.11.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  


flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
    favicon: true  # Esto genera el favicon automáticamente
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48


flutter:
  assets:
    - lib/models/
  uses-material-design: true

