// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-0JeIMsfMl9kB-Z-VyngISp8LXwdjPzM',
    appId: '1:644919517286:web:79993357912a97da0b8da7',
    messagingSenderId: '644919517286',
    projectId: 'control-gastos-35212',
    authDomain: 'control-gastos-35212.firebaseapp.com',
    storageBucket: 'control-gastos-35212.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrnAbMqCnquGQ4GceiPkCLYC_lUNFFCRU',
    appId: '1:644919517286:android:c41ad3f69b5b70180b8da7',
    messagingSenderId: '644919517286',
    projectId: 'control-gastos-35212',
    storageBucket: 'control-gastos-35212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPtPdk2i5NmOrwlKKf3nawFJ5rPuq0Ko',
    appId: '1:644919517286:ios:bd7adcd0560141b00b8da7',
    messagingSenderId: '644919517286',
    projectId: 'control-gastos-35212',
    storageBucket: 'control-gastos-35212.firebasestorage.app',
    iosBundleId: 'com.ando.devs.controlGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPtPdk2i5NmOrwlKKf3nawFJ5rPuq0Ko',
    appId: '1:644919517286:ios:bd7adcd0560141b00b8da7',
    messagingSenderId: '644919517286',
    projectId: 'control-gastos-35212',
    storageBucket: 'control-gastos-35212.firebasestorage.app',
    iosBundleId: 'com.ando.devs.controlGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-0JeIMsfMl9kB-Z-VyngISp8LXwdjPzM',
    appId: '1:644919517286:web:4922bc54a6fe36510b8da7',
    messagingSenderId: '644919517286',
    projectId: 'control-gastos-35212',
    authDomain: 'control-gastos-35212.firebaseapp.com',
    storageBucket: 'control-gastos-35212.firebasestorage.app',
  );
}
